version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tele-backend
    ports:
      - "8048:8048"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/db  # 持久化 SQLite 数据库文件
    environment:
      DATABASE_URL: sqlite:///app/db/db.sqlite3
    command: python main.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tele-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend

volumes:
  sqlite_data:
